#! /bin/bash

if [[ $(uname -m) == "x86_64" ]]
then
    wget --backups=0 "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-3.2.7.tgz"
    tar -zxvf ./mongodb-linux-x86_64-ubuntu1604-3.2.7.tgz --strip-components=1
else
    wget --backups=0 "https://fastdl.mongodb.org/linux/mongodb-linux-arm64-ubuntu1604-3.6.21.tgz"
    tar -zxvf ./mongodb-linux-arm64-ubuntu1604-3.6.21.tgz --strip-components=1 --no-same-owner
    rm ./mongodb-linux-arm64-ubuntu1604-3.6.21.tgz
fi
